ENV: dev
DEBUG: True
use_reloader: False

# login cookie expirse
# REMEMBER_COOKIE_DURATION: timedelta(hours=2)
# DB Config
DBUSER: "root"
DBPASS: "root"
DBHOST: "localhost"
DNNAME: "salt"

# DB String
SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://root:root@mysql-db/salt?charset=utf8'
SQLALCHEMY_TRACK_MODIFICATIONS: False
# SaltAPI
# SALT_URL: 'https://salt-master:8080/'
SALT_URL: 'https://localhost:8080/'
SALT_USER: 'diana'
SALT_PASS: 'secret'
SALT_EAUTH: 'mysql'
